

services:
  server:
    build: ./server
    container_name: tableease-server
    ports:
      - "5050:5050"
    env_file:
      - ./server/.env

  client:
    build: ./client
    container_name: tableease-client
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env.local
    depends_on:
      - server