"use client";

import Image from "next/image";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { verifyLoginMfa } from "../lib/api";

export default function MfaPage() {
  const router = useRouter();

  const [code, setCode] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  async function handleVerify(e: React.FormEvent) {
    e.preventDefault();

    setError("");

    if (code.length !== 6) {
      setError("Please enter the 6-digit verification code.");
      return;
    }

    try {
      setLoading(true);

      const email = localStorage.getItem("mfaEmail");

      if (!email) {
        throw new Error("Login session expired. Please login again.");
      }

      const response = await verifyLoginMfa({
        email,
        token: code,
      });

      localStorage.setItem("token", response.data.token);
      localStorage.setItem(
        "user",
        JSON.stringify(response.data.user)
      );

      localStorage.removeItem("mfaEmail");

      if (response.data.user.role === "admin") {
        router.push("/admin/dashboard");
      } else {
        router.push("/dashboard");
      }
    } catch (err) {
      if (err instanceof Error) {
        setError(err.message);
      } else {
        setError("Invalid verification code.");
      }
    } finally {
      setLoading(false);
    }
  }
return (
  <div className="flex min-h-screen">

    {/* Left Side */}
    <div className="relative hidden lg:flex w-1/2">
      <img
        src="https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80"
        alt="Restaurant"
        className="h-full w-full object-cover"
      />

      {/* Dark Overlay */}
      <div className="absolute inset-0 bg-black/45" />

      {/* Text */}
      <div className="absolute left-16 top-1/2 -translate-y-1/2 text-white max-w-md">
        <p className="mb-4 text-sm font-semibold tracking-[0.35em] text-yellow-500">
          WELCOME TO LUMINA
        </p>

        <h1 className="text-6xl font-bold leading-tight">
          Secure Your
          <br />
          Account
          <br />
          With MFA
        </h1>

        <p className="mt-8 text-lg leading-8 text-gray-200">
          Protect your account with an extra layer of security.
          Enter the verification code generated by your authenticator
          app to continue.
        </p>
      </div>
    </div>

    {/* Right Side */}
    <div className="flex flex-1 items-center justify-center bg-[#fafafa] px-6">

      <div className="w-full max-w-md rounded-2xl border border-neutral-100 bg-white p-10 shadow-xl">

        <div className="mb-8 text-center">
          <h1 className="text-3xl font-extrabold tracking-[0.2em] text-neutral-900">
            LUMINA
          </h1>

          <p className="mt-3 text-sm font-light text-neutral-500">
            Multi-Factor Authentication
          </p>
        </div>

        <form onSubmit={handleVerify} className="space-y-6">

          <div>
            <label className="mb-2 block text-sm font-semibold text-neutral-800">
              Verification Code
            </label>

            <input
              type="text"
              maxLength={6}
              value={code}
              onChange={(e) =>
                setCode(e.target.value.replace(/\D/g, ""))
              }
              placeholder="Enter 6-digit code"
              className="w-full rounded-md border border-neutral-300 bg-white px-4 py-3 text-sm text-center tracking-[0.25em] text-neutral-900 placeholder-neutral-400 outline-none transition focus:border-yellow-600 focus:ring-1 focus:ring-yellow-600"
            />
          </div>

          {error && (
            <p className="text-sm text-red-600">
              {error}
            </p>
          )}

          <button
            type="submit"
            disabled={loading}
            className="w-full rounded-md bg-neutral-950 py-3 text-sm font-semibold tracking-wide text-white transition hover:bg-yellow-600 disabled:cursor-not-allowed disabled:opacity-50"
          >
            {loading ? "Verifying..." : "Verify Code"}
          </button>

        </form>
      </div>

    </div>
  </div>
);
}